export const ADD_TRANSLATION = 'ADD_TRANSLATION';
export const REMOVE_TRANSLATION = 'REMOVE_TRANSLATION';
export const UPDATE_TRANSLATION = 'UPDATE_TRANSLATION';
export const VOTE_UP_TRANSLATE = 'VOTE_UP_TRANSLATE';
export const VOTE_DOWN_TRANSLATE = 'VOTE_DOWN_TRANSLATE';
export const ADD_COMMENT = 'ADD_COMMENT';
export const REMOVE_COMMENT = 'REMOVE_COMMENT';
